app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# -------------------------------------------------------------------


urlpatterns = [
    path('',include(('bases.urls','bases'),namespace='bases' )),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    # ----------------------------------------------------------------------
    
]

admin.site.site_header="Municipio de Quilanga" # administracion de emprendimientos
admin.site.index_title="Sitio Administrativo"
admin.site.site_title="Emprendimientos Municipio de Quilanga"

urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/bases/urls.py
from django.urls import path
from bases.views import listado_categorias
from bases.views import lista_emprendimientos_categoria 
from bases.views import lista_productos_emprendimiento 
from bases.views import contacto_municipio 
from bases.views import send_user_mail
from bases.views import lista_propietarios
# PARA CATEGORIAS
from bases.views import autosuggest
from bases.views import listado_categorias_buscar

# PARA EMPRENDIMIENTOS

# PARA PRODUCTOS
from bases.views import autocomplete
from bases.views import listado_productos_buscar

handler404 = 'bases.views.mi_error_404'

urlpatterns = [
    path('', listado_categorias, name="listado_categorias"),
    path('emprendimientos/<int:pk>/', lista_emprendimientos_categoria, name="lista_emprendimientos_categoria"),
    path('productos/<int:pk>/', lista_productos_emprendimiento,name="lista"),
    path('propietarios/<int:pk>/', lista_propietarios,name="propietarios"),
    path('contacto/municipio-quilanga/', contacto_municipio, name="contacto_municipio"),
    path('enviarcorreo-emprendedor/<int:pk>/', send_user_mail, name="enviarcorreo"),
# PARA BUSCAR CATEGORIAS
    path('autosuggest', autosuggest, name="autosuggest"),
    path('listado_categorias_buscar', listado_categorias_buscar, name="listado_categorias_buscar"),

# PARA BUSCAR PRODUCTOS
    path('autocomplete', autocomplete, name="autocomplete"),
    path('listado_productos_buscar', listado_productos_buscar, name="listado_productos_buscar"),
]

app/bases/models.py
from django.db import models

# Create your models here.

class Emprendedor(models.Model):
    cedula=models.CharField(max_length=10, verbose_name="cédula", unique=True)
    nombres=models.CharField(max_length=20)
    apellidos=models.CharField(max_length=20)
    direccion=models.CharField(max_length=150, verbose_name="dirección")
    email=models.EmailField(unique=True)
    imagen=models.ImageField(null=True, blank=True, upload_to='Emprendedores')
    tfno=models.CharField(max_length=10, verbose_name="teléfono")
    facebook=models.CharField(max_length=100, null=True, blank=True)
    twitter=models.CharField(max_length=100, null=True, blank=True)
    instagram=models.CharField(max_length=100, null=True, blank=True)
    whatsapp=models.CharField(max_length=100, null=True, blank=True)
    
    def __str__(self):
        return '{}'.format(self.email)
        # return "Emprendedor con cédula %d y apellido %s" % (self.cedula, self.apellidos)

    class Meta:
        verbose_name_plural= "Emprendedores"
        ordering=['nombres', "apellidos"]



class Categoria(models.Model):
    nombre= models.CharField(max_length=50, help_text='Nombre de Categoría', unique=True)
    descripcion=models.TextField(max_length=100, null=True, blank=True)
    imagen=models.ImageField(null=True, blank=True, upload_to="Categorias")

    def __str__(self):
        return '{}'.format(self.nombre)

    class Meta:
        verbose_name_plural='Categorías'
        ordering=['nombre']



class Emprendimiento(models.Model):
    nombre=models.CharField(max_length=50)
    descripcion=models.TextField(max_length=500, help_text='Descripción del Emprendimiento', verbose_name="descripción", null=True, blank=True)
    direccion=models.CharField(max_length=150, help_text='Dirección del emprendimiento', verbose_name='dirección')
    categoria=models.ForeignKey(Categoria, on_delete=models.CASCADE)
    fecha_creacion=models.DateField(verbose_name='fecha de creación')
    imagen=models.ImageField(null=False, blank=False, upload_to='Emprendimientos')
    emprendedores=models.ManyToManyField(Emprendedor)

    def __str__(self):
        return '{}'.format(self.nombre)

    class Meta:
        ordering=['nombre']
        verbose_name_plural= "Emprendimientos"



class Producto(models.Model):
    codigo=models.CharField(max_length=20, verbose_name="código", unique=True)
    nombre=models.CharField(max_length=30)
    marca=models.CharField(max_length=20)
    descripcion=models.TextField(max_length=500, help_text='Descripción del Producto', verbose_name="descripción", null=True, blank=True)
    precio=models.FloatField(default=0)
    emprendimiento= models.ForeignKey(Emprendimiento, on_delete=models.CASCADE)
    imagen=models.ImageField(null=False, blank=False, upload_to='Productos')

    def __str__(self):
        return '{}'.format(self.nombre)

    class Meta:
        verbose_name_plural="Productos"
        ordering=['nombre']



class Contacto(models.Model):
    asunto=models.CharField(max_length=120)
    nombre=models.CharField(max_length=30)
    email=models.EmailField()
    telefono=models.CharField(max_length=10, verbose_name="teléfono")
    mensaje=models.TextField()

    def __str__(self):
        return '{}'.format(self.nombre)

app/bases/forms.py
from django import forms
from django.forms import ModelForm
from .models import Contacto

        
class ContactoForm(forms.ModelForm):
    
    class Meta:
        model=Contacto
        fields=["nombre", "email", "telefono", "mensaje"]

app/bases/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from bases.models import *
from .forms import ContactoForm
from django.conf import settings
from django.core.mail import send_mail, BadHeaderError
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse

from django.http import JsonResponse
# from rest_framework.response import Response
from django.db.models import Q


# Create your views here.

def send_user_mail(request, pk):
    correo = get_object_or_404(Emprendedor, pk=pk)
    e = Emprendedor.objects.get(email=correo.email)
    
    if request.method=='POST':
        subject=request.POST['asunto']
        nombre=request.POST['nombre']
        telef=request.POST['telefono']
        
        message=request.POST['mensaje']+"\n" + "\nRemitente:\n"+nombre+"\n\nEmail: \n"+request.POST['email']+"\n\nTeléfono: \n"+telef
        
        email_form = settings.EMAIL_HOST_USER
        
        if subject and message and email_form:
            try:
                send_mail(subject, message, email_form, [e])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
        # recipient_list=['cristianfroning@gmail.com']
        # send_mail(subject, message, email_form, recipient_list)
        return render (request, 'bases/mensaje_enviado.html')

    return render(request, 'bases/contacto.html')

# este será reeemplazo de la funcion listado_emprendimientos
def listado_categorias(request):
    busqueda = request.GET.get("buscar")
# presentacion de todas las cat existentes
    lista_categ=Categoria.objects.all()
# paginación
    paginator=Paginator(lista_categ, 15)
    pagina=request.GET.get("page") or 1
    categ=paginator.get_page(pagina)
    pagina_actual=int(pagina)
    paginas=range(1, categ.paginator.num_pages +1)

    if busqueda:
        categ = Categoria.objects.filter(
            Q(nombre__icontains = busqueda) |
            Q(descripcion__icontains = busqueda)
        ).distinct()

    return render(request, 'bases/listado_categorias.html', {'categ':categ, 'paginas':paginas, 'pagina_actual':pagina_actual})

def autosuggest(request):
    # print(request.GET)
    busque = request.GET.get('term')
    print(busque)
    queryset = Categoria.objects.filter(nombre__icontains=busque)
    mylist = []
    mylist += [x.nombre for x in queryset]
    return JsonResponse(mylist, safe=False)

def listado_categorias_buscar(request):
    busqueda = request.GET.get("buscar")
    queryset = Categoria.objects.filter(
        Q(nombre__icontains=busqueda) |
        Q(descripcion__icontains=busqueda)
    ).distinct()
    mylist = []
    mylist += [x.nombre for x in queryset]
    return JsonResponse(mylist, safe=False)

# ---------------------------------------------------- FUNCIONES PARA EMPRENDIMIENTOS -----------------------------------------------------

def lista_emprendimientos_categoria(request, pk):
    busqueda = request.GET.get("buscar")
# listado de los emprendimientos por categoria seleccionada
    cat = get_object_or_404(Categoria, pk=pk)
    lista_emprendimientos = Emprendimiento.objects.filter(categoria=cat)
# paginación
    paginator=Paginator(lista_emprendimientos, 10)
    pagina=request.GET.get("page") or 1
    emprendimientos=paginator.get_page(pagina)
    pagina_actual=int(pagina)
    paginas=range(1, emprendimientos.paginator.num_pages +1)
    
    
    if busqueda:
        emprendimientos = Emprendimiento.objects.filter(
            Q(nombre__icontains = busqueda) |
            Q(descripcion__icontains = busqueda)
        ).distinct()

    return render(request, 'bases/listado_emprendimiento.html', {'emprendimientos':emprendimientos, 'paginas':paginas, 'pagina_actual':pagina_actual})

def lista_productos_emprendimiento(request, pk):
    # presentamos los productos por medio del filtro
    emprend = get_object_or_404(Emprendimiento, pk=pk)
    lista_productos = Producto.objects.filter(emprendimiento=emprend)
    empddr= emprend.emprendedores.all()
    paginator=Paginator(lista_productos, 10)
    pagina=request.GET.get("page") or 1
    productos=paginator.get_page(pagina)
    pagina_actual=int(pagina)
    paginas=range(1, productos.paginator.num_pages +1)

    busqueda = request.GET.get("buscar")
    if busqueda:
        productos = Producto.objects.filter(
            Q(nombre__icontains=busqueda) |
            Q(descripcion__icontains=busqueda)
        ).distinct()

    return render(request, 'bases/listado_productos.html', {'productos':productos, 'emp':empddr, 'pagina_actual':pagina_actual, 'paginas':paginas})


def autocomplete(request):
    # print(request.GET)
    busquepro = request.GET.get('termpro')
    print(busquepro)
    queryset = Producto.objects.filter(nombre__icontains=busquepro)
    mylist = []
    mylist += [x.nombre for x in queryset]
    return JsonResponse(mylist, safe=False)


def listado_productos_buscar(request):
    busqueda = request.GET.get("buscar")
    queryset = Producto.objects.filter(
        Q(nombre__icontains=busqueda) |
        Q(descripcion__icontains=busqueda)
    ).distinct()
    mylist = []
    mylist += [x.nombre for x in queryset]
    return JsonResponse(mylist, safe=False)
 


# ------------------------------------------------ para listar propietarios de cada emprendimiento -----------------------------------------

def lista_propietarios(request, pk):
    # presentamos los productos por medio del filtro
    emprend = get_object_or_404(Emprendimiento, pk=pk)
    # lista_productos = Producto.objects.filter(emprendimiento=emprend)
    empddr= emprend.emprendedores.all()
    
    return render(request, 'bases/propietarios.html', {'emp':empddr})


#---------------------------------------------------------- apartado para la función de contacto-municipio-----------------------------------------------
# def mensaje_enviado(request):
#     return render(request, 'bases/mensaje_enviado.html')

def contacto_municipio(request):
    if request.method=='POST':
        correo=request.POST['email']
        nombre=request.POST['nombre']
        telef=request.POST['telefono']
        subject=request.POST['asunto']
        message=request.POST['mensaje']+" | Remitente: "+nombre+" email: "+ correo+" teléfono: "+telef
        email_form = settings.EMAIL_HOST_USER
        recipient_list=['emprendimientosquilanga@gmail.com']
        send_mail(subject, message, email_form, recipient_list)
        
        return render (request, 'bases/mensaje_enviado.html')
    return render(request, 'bases/contacto.html')

# ----------------------------------------------------PAGINA NO ENCONTRADA--------------------------------------------------- #
# from django.template import RequestContext
# from django.shortcuts import render_to_response

def mi_error_404(request, exception):
    return render(request, 'bases/404.html')

app/bases/templates/bases/barra_nav.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div id="sidemenu" class="menu-collapsed">
        
        <div id="header">
            <div id="title"><span>vida mRR</span></div>
            <div id="menu-btn">
                <div class="btn-humburger"></div>
                <div class="btn-humburger"></div>
                <div class="btn-humburger"></div>
            </div>
        </div>

        <!-- profile -->
        <div id="perfil">
            <div id="foto"><img src="../../../static/base/assets/img/eliminar.png" alt=""></div>
            <div id="name"><span>Emprendimientos Quilanga</span></div>
        </div>
        <!-- items -->
        <div id="menu-item">
            <div class="item">
                <a href="#">
                    <div class="icon"><img src="../../../static/base/assets/img/eliminar.png" alt=""></div>
                    <div class="title"><span>Cloud Services</span></div>
                </a>
            </div>
        </div>
    </div>
</body>
</html>

app/bases/templates/bases/listado_categorias.html
{% extends 'base/base.html' %}
{%load static%}

{% block listado_category%}

<style>

    /* #buscador {
        padding-bottom: 3rem;
    }

    .boton {
        height: 40px;
        border-radius: 10px;
        position: relative;
        right: 5px;
    } */

    .boton {
        height: 6vh;
    }

    .dropdown-menu>li>a:hover,
    .dropdown-menu>li>a:focus {
        background-color: #e8e8e8;
        background-image: -webkit-linear-gradient(top, #f5f5f5 0%, #e8e8e8 100%);
        background-image: -o-linear-gradient(top, #f5f5f5 0%, #e8e8e8 100%);
        background-image: -webkit-gradient(linear, left top, left bottom, from(#f5f5f5), to(#e8e8e8));
        background-image: linear-gradient(to bottom, #f5f5f5 0%, #e8e8e8 100%);
        filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#fff5f5f5', endColorstr='#ffe8e8e8', GradientType=0);
        background-repeat: repeat-x;
    }

    .dropdown-menu>.active>a,
    .dropdown-menu>.active>a:hover,
    .dropdown-menu>.active>a:focus {
        background-color: #2e6da4;
        background-image: -webkit-linear-gradient(top, #337ab7 0%, #2e6da4 100%);
        background-image: -o-linear-gradient(top, #337ab7 0%, #2e6da4 100%);
        background-image: -webkit-gradient(linear, left top, left bottom, from(#337ab7), to(#2e6da4));
        background-image: linear-gradient(to bottom, #337ab7 0%, #2e6da4 100%);
        filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ff337ab7', endColorstr='#ff2e6da4', GradientType=0);
        background-repeat: repeat-x;
    }

    .bootstrap-datetimepicker-widget {
        list-style: none;
    }

    .bootstrap-datetimepicker-widget.dropdown-menu {
        display: block;
        margin: 2px 0;
        padding: 4px;
        width: 19em;
    }
/* ------------------------------------------------------------------------------- */
    section {
        background: white;
    }

    #cont {
        width: 90%;
        height: auto;
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        margin: auto;
    }

    #cont .card {
        width: 170px;
        height: auto;
        border-radius: 10px;
        overflow: hidden;
        margin: 5px;
        text-align: center;
        transition: all 0.3s;
    }

    #cont .card:hover {
        color: white;
        transform: translateY(-5px);
        box-shadow: 0 18px 21px rgba(3, 7, 250, 0.774);
    }
    
    #cont .card:hover p {
        color: rgba(3, 7, 250, 0.774);
    }

    #cont .card img {
        width: 160px;
        height: 160px;
        margin-top: 4px;
        border-radius: 10px;
        background-size: cover;
    }

    .row {
        justify-content: center;
    }
    
    #resultados {
        color: #024b8b;
        left: 1.5%;
        border: solid aliceblue;
        opacity: 0.9;
        font-family: 'Montserrat';
        font-size: x-large;
        width: 60.5rem;
        font-weight: 800;
    }

</style>

<h1 class="text-center" id="portfolio">PORTAFOLIO</h1>
<hr>
<h2 class="text-center">Hecha un vistazo a nuestra lista de categorías</h2>
<hr>
<br>

<div class="container listado_categorias">
    <div class="row">
        <div class="col-md-12 search">
            <form method="GET">
                <div id="custom-search-input">
                    <div class="input-group col-md-12">
                        <input type="text" autocomplete="off" class="form-control prefix" id="tags"
                            placeholder="Buscar..." name="buscar">
                        <div id="resultados" name="datetimepicker"
                            class="dropdown-menu dropdown-menu bottom pull-right bootstrap-datetimepicker-widget">
                        </div>
                        <span class="input-group-list">
                            <i class="icon icon-search"></i>
                            <button type="submit" id="botonbuscar" class="boton btn-success">Buscar</button>
                        </span>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<br>
<br>

<script type="text/javascript">

        $("#resultados").hide();
        $('#tags').keyup(function (e) {
            $("#resultados").text("");
            consulta = $("#tags").val();
            $.ajax({
                data: { 'term': consulta },
                url: "{% url 'bases:autosuggest' %}",
                type: 'get',
                success: function (data) {
                    console.log(data)
                    $("#resultados").text("");
                    for (i = 0; i < data.length; i++) {
                        group = data;
                        $("#resultados").show();
                        $("#resultados").append('<li style=' + '"list-style: none;"' + 'role=' + '"button"' + 'onclick=' + '"buscar1(' + i + ')"' + '>' + data[i] + "</li>");
                    }
                    if (consulta == "") { $("#resultados").text(""); }
                },
                error: function (message) {
                    $("#resultados").text("");
                },
            });
        });


        function buscar1(par) {
            console.log("ingresa a buscar==============" + par)
            console.log(group[par]);

            $('#tags').val(group[par]);
            $('#botonbuscar').click();

            // $.ajax({
            //     data: { 'buscar': group[par] },
            //     url: "{% url 'bases:listado_categorias_buscar' %}",
            //     type: 'get',
            //     success: function (data) {
            //         console.log("ingresa a succes 1")
            //         console.log(data)
            //         //$('.listado_categorias').html(data)
            //         categ = data;
            //     },
            //     error: function (message) {
            //         console.log(message)
            //     },
            // });
        }

</script>

{% if categ %}
<div class="row">
    {% for cat in categ %}
    <div class="col-lg-4 col-sm-6 mb-4">
        <div id="cont">
            <div class="card">
                <a href="{% url 'bases:lista_emprendimientos_categoria' pk=cat.pk %}">
                    <img class="img-fluid" src='{{cat.imagen.url}}' alt="" />
                    <p style = "text-transform:uppercase; font-size: 1vmax; font-weight: bolder; margin-top: 10px;">{{cat.nombre}}</p>
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<hr>
<div class="paginator">
    {% include "bases/paginacion_categ.html"%}
</div>
{% else %}
<div class="alert alert-danger text-center">No hay Categorías que mostrar por el momento</div>
{% endif %}

{% endblock %}

app/bases/templates/bases/listado_emprendimiento.html
{% extends 'base/base.html' %}
{%load static%}
{%block slider%}{%endblock%}
{%block nav%}{%endblock%}

{% block listado_emprendimientos %}
<style>
    #buscador {
        padding-bottom: 3rem;
    }

    .boton {
        height: 40px;
        border-radius: 10px;
        position: relative;
        right: 5px;
    }

    section {
        background: white;
    }

    #cont {
        width: 100%;
        height: auto;
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        margin: auto;
    }

    .portfolio-item {
        justify-content: center;
    }

    #cont .card {
        width: 300px;
        height: auto;
        border-radius: 10px;
        overflow: hidden;
        margin: 5px;
        text-align: center;
        transition: all 0.3s;
    }

    #cont .card:hover {
        color: white;
        transform: translateY(-5px);
        box-shadow: 0px 15px 25px rgba(3, 7, 250, 0.774);
    }

    #cont .card:hover h4 {
        color: rgba(3, 7, 250, 0.774);
    }

    #cont .card p {
        padding-top: 10px;
        font-size: 25px;
    }

    #cont .card img {
        width: 300px;
        height: 180px;
        border-radius: 6px;
        background-size: cover;
    }

    .contenedor {
        height: auto;
    }

    .contenedor figure {
        position: relative;
        height: auto;
        width: auto;
        overflow: hidden;
        margin: 5px;
        border-radius: 6px;
        cursor: pointer;
        background: #fff;
    }

    .contenedor figure img {
        width: 250px;
        height: 250px;
        transition: all 500ms ease-out;
    }

    .contenedor figure .capa {
        position: absolute;
        top: 0;
        width: 100%;
        height: 100%;
        background: rgba(49, 49, 49, 0.651);
        transition: all 500ms ease-out;
        opacity: 0;
        visibility: hidden;
        text-align: center;
    }

    .contenedor figure:hover>.capa {
        opacity: 1;
        visibility: visible;
    }

    .contenedor figure:hover>.capa h3 {
        margin-top: 70px;
        margin-bottom: 15px;
    }

    .contenedor figure:hover>img {
        transform: scale(1.3);
    }

    .contenedor figure .capa h3 {
        color: rgb(255, 245, 102);
        font-weight: 400;
        margin-bottom: 120px;
        transition: all 500ms ease-out;
        margin-top: 30px;
    }

    .contenedor figure .capa p {
        color: rgb(255, 255, 255);
        font-size: 15px;
        line-height: 1.5;
        width: 100%;
        max-width: 220px;
        margin: auto;
    }

    .contacto {
        height: 40px;
        width: 100%;
        justify-content: center;
        display: flex;
    }

    .contacto .contact-text {
        height: auto;
        text-decoration: none;
        font-size: 20px;
    }

    .contacto #boton_empre {
        margin-left: 10px;
        width: 30px;
        height: 30px;
        border-radius: 100%;
        display: flex;
        justify-content: center;
        transition: 0.3s ease-in-out;
    }

    .contenedor .contacto #boton_empre .contact {
        width: 200px;
        font-size: 1vmax;
    }

    .contacto #boton_empre:hover {
        background: linear-gradient(to top, rgb(17, 247, 55), rgb(3, 0, 172));
        position: relative;
        font-size: 20px;
        transform: rotate(360deg);
        height: 35px;
        width: 35px;
        cursor: pointer;
    }

    .container-emp {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
    }

    .seccion-emp {
        justify-content: center;
    }

    #cont .card .contenedor figure .capa .p2 {
        padding-top: 20px;
        font-size: 1vmax;
        text-align: justify;
        visibility: hidden;
        transition: 0.5s ease-in-out;
    }

    #cont .card .contenedor:hover figure .capa .p2 {
        font-size: 1vmax;
        text-align: justify;
        padding-top: 10px;
        visibility: visible;
        transform: translateY(-5px);
    }
</style>

<br>
<br>
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="../../"><img
                src="{% static 'base/assets/img/logo_municipal.png' %}" alt="" />
        </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
            aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars ml-1"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav text-uppercase ml-auto">
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="/">Volver a portafolio</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="/admin/">Iniciar Sesión</a></li>
            </ul>
        </div>
    </div>
</nav>

<section class="seccion-emp">
    <div class="text-center">
        <h2 class="section-heading text-uppercase">Emprendimientos</h2>
        <hr>
    </div>
    {% if emprendimientos %}
    <div class="container-emp">
        {% for emprendimientos in emprendimientos %}
        <div class="col-lg-4 col-sm-6 mb-4">
            <div class="portfolio-item">
                <div id="cont">
                    <div class="card">
                        <a class="contenedor" href="{% url 'bases:lista' pk=emprendimientos.pk %}">
                            {% if emprendimientos.imagen %}
                            <figure>
                                <img class="img-fluid" src='{{emprendimientos.imagen.url}}' alt="" />
                                <div class="capa">
                                    {% if emprendimientos.descripcion %}
                                    <p class="p2">{{emprendimientos.descripcion}}</p>
                                    {% else %}
                                    <h3 class="p1">{{emprendimientos.nombre}}</h3>
                                    {% endif %}
                                </div>
                            </figure>
                            {% endif %}
                            <h4 class="nombre_emp">{{emprendimientos.nombre}}</h4>

                            <hr>
                            <div class="contacto">
                                <a class="contact-text">Contáctanos</h5>
                                    <a role="button" id="boton_empre" class="btn btn-warning"
                                        onclick="abrir_modal_presentar('{% url 'bases:propietarios' pk=emprendimientos.pk %}')">
                                        <i id="icono_pro" class="fas fa-id-card"></i>
                                    </a>
                                </a>
                            </div>

                        </a>
                    </div>

                </div>
                <div class="modal fade" id="presentar" role="dialog"></div>
            </div>
        </div>

        <div class="modal fade" id="presentar" role="dialog">
            <!-- Apartado necesario para que se presente el modal según el id -->
        </div>

        {% block extrajs %}
        <script type="text/javascript">
            var $ = jQuery.noConflict();
            function abrir_modal_presentar(url) {
                $('#presentar').load(url, function () {
                    $(this).modal('show');
                });
            }
        </script>
        {% endblock %}
        {% endfor %}
    {% else %}
    <div class="alert alert-danger text-center">No hay emprendimientos que mostrar por el momento</div>
    {% endif %}
    </div>
    <hr>
    {%include "bases/paginacion_emp.html"%}
</section>
{%endblock%}

app/bases/templates/bases/nuevo_producto.html
{% block contenido %}

<h2>Nuevo Producto</h2>

<form action="" method="POST" enctype="multipart/form-data">
    {%csrf_token%}
    <table>
        {{ form.as_table }}
    </table>
    <input type="reset" value="Limpiar">
    <input type="submit" value="Guardar">
</form>
{{mensaje}}

{% endblock %}

app/bases/templates/bases/paginacion_categ.html
{%block slider%}{%endblock%}

<style>
    .barra_pag {
        padding: 30px;
    }

    .row {
        justify-content: center;

    }

    .fila {
        display: flex;
        flex-wrap: nowrap;
    }

    .pagination {
        background: white;
        justify-content: center;    
    }

    .page-item a {
        background: #008000;
    }
</style>

<div class="pag">
    <ul class="pagination">
        {%if categ.has_previous %}
        <li class="page-item">
            <a href="?page=1" class="page-link">Primera página</a>
        </li>

        <li class="page-item">
            <a href="?page={{categ.previous_page_number}}" class="page-link">&laquo;</a>
        </li>
        {%endif%}

        {%if categ.has_next %}
        <li class="page-item">
            <a href="?page={{categ.next_page_number}}" class="page-link">&raquo;</a>
        </li>

        <li class="page-item">
            <a href="?page={{categ.paginator.num_pages}}" class="page-link">Última página</a>
        </li>
        {%endif%}
    </ul>
</div>