app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# -------------------------------------------------------------------


urlpatterns = [
    path('',include(('bases.urls','bases'),namespace='bases' )),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    # ----------------------------------------------------------------------
    
]

admin.site.site_header="Municipio de Quilanga" # administracion de emprendimientos
admin.site.index_title="Sitio Administrativo"
admin.site.site_title="Emprendimientos Municipio de Quilanga"

urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/bases/urls.py
from django.urls import path
from bases.views import listado_categorias
from bases.views import lista_emprendimientos_categoria 
from bases.views import lista_productos_emprendimiento 
from bases.views import contacto_municipio 
from bases.views import send_user_mail
from bases.views import lista_propietarios
# PARA CATEGORIAS
from bases.views import autosuggest
from bases.views import listado_categorias_buscar

# PARA EMPRENDIMIENTOS

# PARA PRODUCTOS
from bases.views import autocomplete
from bases.views import listado_productos_buscar

handler404 = 'bases.views.mi_error_404'

urlpatterns = [
    path('', listado_categorias, name="listado_categorias"),
    path('emprendimientos/<int:pk>/', lista_emprendimientos_categoria, name="lista_emprendimientos_categoria"),
    path('productos/<int:pk>/', lista_productos_emprendimiento,name="lista"),
    path('propietarios/<int:pk>/', lista_propietarios,name="propietarios"),
    path('contacto/municipio-quilanga/', contacto_municipio, name="contacto_municipio"),
    path('enviarcorreo-emprendedor/<int:pk>/', send_user_mail, name="enviarcorreo"),
# PARA BUSCAR CATEGORIAS
    path('autosuggest', autosuggest, name="autosuggest"),
    path('listado_categorias_buscar', listado_categorias_buscar, name="listado_categorias_buscar"),

# PARA BUSCAR PRODUCTOS
    path('autocomplete', autocomplete, name="autocomplete"),
    path('listado_productos_buscar', listado_productos_buscar, name="listado_productos_buscar"),
]

app/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<!-- #28a745 -->
<style>

    #subir{
        position: fixed;
        right: 25px;
        bottom: 120px;
        z-index: 2;
        border-radius: 50%;
        height: 70px;
        width: 60px;
    }

    #subir > #flecha{
        height: 30px;
        width: 30px;
        position: absolute;
        right: 25px;
    }

    footer {
        text-align: center;
        background: #008000;
        /* position: absolute; */
        /* bottom: unset; */
        position: absolute;
        right: 0%;
        bottom: unset;
        border-bottom: solid;
        width: 100%;
    }

    .seccion {
        height: 100%;
    }

    .navbar .container .navbar-brand>i {
        margin: 10px;
        font-family: 'Dancing Script', cursive;
    }

    @media screen and (max-width: 992px) {
        .navbar .container .navbar-brand>i {
            display: none;
        }
    }
</style>

{%block header%}

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Emprendimientos - Municipio de Quilanga</title>

    <link rel="icon" type="image/x-icon" href="{% static 'base/assets/img/logo_municipal.png' %}" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" type="text/javascript"></script>
    <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic" rel="stylesheet"
        type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
    
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap" rel="stylesheet">
    <!-- Core theme CSS (includes Bootstrap)-->
    
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    
    <link href="{% static 'base/css/styles.css' %}" rel="stylesheet" />
</head>
{%endblock%}

<body id="page-top">
    <!-- Navigation-->
    {%block nav%}
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="../../">
                <img src="{% static 'base/assets/img/logo_municipal.png' %}" alt="" />
                <i>Emprende Quilanga ...te apoyamos!!!</i>
            </a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars ml-1"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav text-uppercase ml-auto">
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="/admin/">Iniciar Sesión</a></li>
                </ul>
            </div>
        </div>
    </nav>
    {%endblock nav%}
    {%block slider%}
    <!-- Masthead-->
    <header class="masthead">
        <div class="container">
            <div class="masthead-subheading">Bienvenido a Nuestro Portafolio de Emprendimientos!</div>
            <div class="masthead-heading text-uppercase">Es un placer conocerte!</div>
            <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="#portfolio">Dime más</a>
        </div>
    </header>
    {%endblock slider%}
    <section class="page-section">
        
        <!-- Portfolio Grid-->
        <div class="seccion">
            {% block listado_emprendimientos %} {% endblock %}
            {% block listado_productos %} {% endblock %}
            {%block listado_propietarios%}{%endblock%}
            {% block listado_category%} {% endblock %}
            {% block contacto%} {% endblock %}
            {% block content %} {% endblock %}
            {% block gracias %}{%endblock%}
            
            {% block extrajs %} {% endblock %}
        </div>
        
    </section>
    
    <!-- <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="#portfolio" id="subir"><i id="flecha" class="fas fa-arrow-circle-up"></i></a> -->

    {%block footer%}
    <!-- Footer-->
    <footer class="footer py-4">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-4 text-lg-left">
                    <h6>Copyright © Your Website 2021</h6>
                </div>
                <div class="col-lg-4 my-3 my-lg-0">
                    <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="{% url 'bases:contacto_municipio'%}"><i
                            class="fa fa-envelope"></i></a>
                </div>
                <div class="col-lg-4 text-lg-right">
                    <a class="mr-3" href="#!">Municipio de Quilanga</a>
                </div>
            </div>
        </div>
    </footer>
    {% endblock %}

    <!-- Bootstrap core JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"
        type="text/javascript"></script>
    <!-- Contact form JS-->
    <script src="{% static 'base/assets/mail/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'base/assets/mail/contact_me.js' %}"></script>
    <!-- Core theme JS-->
    <script src="{% static 'base/js/scripts.js' %}"></script>
    
    <script src="{% static 'base/js/validacion.js' %}" charset="utf-8"></script>
    <!-- Autocompletado -->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

</body>

</html>